"""Unit tests for date.arithmetic.

Oracles: the stdlib datetime module (proleptic Gregorian, ISO weeks) for a
broad sweep over years 1-9999, literature anchors for the JDN epoch, and
sxtwl-derived goldens for the sexagenary day pillar (see golden/gen_pillars.py).
"""

import datetime
import unittest

from datex import arithmetic as ar
from datex import Axis, Dizhi, Tiangan, Weekday, Zodiac

_RD_TO_JDN = 1_721_425  # date.toordinal() + this == JDN


class AnchorTest(unittest.TestCase):
    def test_epoch_anchors(self):
        self.assertEqual(ar.civil2jdn(2000, 1, 1), 2_451_545)  # J2000.0
        self.assertEqual(ar.civil2jdn(1970, 1, 1), 2_440_588)  # Unix epoch
        self.assertEqual(ar.civil2jdn(1, 1, 1), 1_721_426)  # RD 1
        # JDN 0 is -4713-11-24 proleptic Gregorian (Nov 24, 4714 BC)
        self.assertEqual(ar.jdn2civil(0), (-4713, 11, 24))

    def test_round_trip_across_eras(self):
        for j in range(-1_000_000, 6_000_000, 9_973):
            y, m, d = ar.jdn2civil(j)
            self.assertEqual(ar.civil2jdn(y, m, d), j)


class StdlibSweepTest(unittest.TestCase):
    def test_sweep_against_datetime(self):
        for ordinal in range(1, 3_652_059, 4_243):
            d = datetime.date.fromordinal(ordinal)
            j = ordinal + _RD_TO_JDN
            self.assertEqual(ar.jdn2civil(j), (d.year, d.month, d.day))
            self.assertEqual(ar.civil2jdn(d.year, d.month, d.day), j)
            self.assertEqual(int(ar.jdn2weekday(j)), d.isoweekday())
            self.assertEqual(ar.jdn2doy(j), d.timetuple().tm_yday)
            iso = d.isocalendar()
            self.assertEqual(ar.jdn2week(j), (iso[0], iso[1]))

    def test_iso_week_edges(self):
        cases = [
            ((2005, 1, 1), (2004, 53)),
            ((2005, 1, 2), (2004, 53)),
            ((2005, 12, 31), (2005, 52)),
            ((2007, 1, 1), (2007, 1)),
            ((2007, 12, 30), (2007, 52)),
            ((2007, 12, 31), (2008, 1)),
            ((2008, 12, 28), (2008, 52)),
            ((2008, 12, 29), (2009, 1)),
            ((2010, 1, 3), (2009, 53)),
        ]
        for (y, m, d), expected in cases:
            self.assertEqual(ar.jdn2week(ar.civil2jdn(y, m, d)), expected, (y, m, d))
            iso = datetime.date(y, m, d).isocalendar()
            self.assertEqual(expected, (iso[0], iso[1]))  # the case itself is sound

    def test_leap(self):
        self.assertTrue(ar.is_leap(2000))
        self.assertTrue(ar.is_leap(2024))
        self.assertTrue(ar.is_leap(-4712))
        self.assertFalse(ar.is_leap(1900))
        self.assertFalse(ar.is_leap(2026))
        self.assertFalse(ar.is_leap(-4700))


class ZodiacTest(unittest.TestCase):
    def test_signs_and_boundaries(self):
        cases = [
            ((1, 19), Zodiac.CAPRICORN), ((1, 20), Zodiac.AQUARIUS),
            ((2, 18), Zodiac.AQUARIUS), ((2, 19), Zodiac.PISCES),
            ((2, 22), Zodiac.PISCES), ((3, 20), Zodiac.PISCES),
            ((3, 21), Zodiac.ARIES), ((4, 14), Zodiac.ARIES),
            ((4, 19), Zodiac.ARIES), ((4, 20), Zodiac.TAURUS),
            ((5, 21), Zodiac.GEMINI), ((6, 12), Zodiac.GEMINI),
            ((6, 20), Zodiac.GEMINI), ((6, 21), Zodiac.CANCER),
            ((7, 5), Zodiac.CANCER), ((7, 22), Zodiac.CANCER),
            ((7, 23), Zodiac.LEO), ((8, 22), Zodiac.LEO),
            ((8, 23), Zodiac.VIRGO), ((9, 20), Zodiac.VIRGO),
            ((9, 22), Zodiac.VIRGO), ((9, 23), Zodiac.LIBRA),
            ((10, 23), Zodiac.SCORPIO), ((11, 21), Zodiac.SCORPIO),
            ((11, 22), Zodiac.SAGITTARIUS), ((12, 8), Zodiac.SAGITTARIUS),
            ((12, 21), Zodiac.SAGITTARIUS), ((12, 22), Zodiac.CAPRICORN),
            ((12, 31), Zodiac.CAPRICORN), ((1, 1), Zodiac.CAPRICORN),
        ]
        for (m, d), sign in cases:
            self.assertEqual(ar.jdn2zodiac(ar.civil2jdn(2001, m, d)), sign, (m, d))


# Generated by tests/golden/gen_pillars.py against sxtwl 2.x (dev-time only;
# the package never imports sxtwl). Columns: y, m, d, 0-based stem, 0-based
# branch. 1949-10-01 is the 甲子 anchor.
_PILLAR_GOLDENS = [
    (1949, 10, 1, 0, 0),
    (2000, 1, 1, 4, 6),
    (2026, 7, 11, 2, 10),
    (1984, 2, 2, 2, 2),
    (1912, 2, 18, 0, 0),
    (2017, 1, 1, 4, 0),
    (1970, 1, 1, 7, 5),
    (2026, 1, 1, 1, 11),
    (1999, 12, 31, 3, 5),
    (2044, 5, 5, 0, 2),
    (1900, 3, 1, 9, 9),
    (2100, 2, 28, 7, 1),
    (1961, 4, 14, 3, 1),
    (1993, 12, 8, 9, 11),
]


class PillarTest(unittest.TestCase):
    def test_goldens(self):
        for y, m, d, tg, dz in _PILLAR_GOLDENS:
            j = ar.civil2jdn(y, m, d)
            self.assertEqual(ar.jdn2cn_day_tiangan(j), list(Tiangan)[tg], (y, m, d))
            self.assertEqual(ar.jdn2cn_day_dizhi(j), list(Dizhi)[dz], (y, m, d))

    def test_anchor(self):
        j = ar.civil2jdn(1949, 10, 1)
        self.assertEqual(ar.pillar_index_of(j), 0)
        self.assertEqual((j + ar.PILLAR_K) % 60, 0)

    def test_cycle_structure(self):
        j = ar.civil2jdn(2026, 7, 11)
        self.assertEqual(ar.jdn2cn_day_tiangan(j + 10), ar.jdn2cn_day_tiangan(j))  # stems: period 10
        self.assertEqual(ar.jdn2cn_day_dizhi(j + 12), ar.jdn2cn_day_dizhi(j))  # branches: period 12
        # the pair only repeats at 60
        pair = ar.jdn2cn_day_tiangan(j), ar.jdn2cn_day_dizhi(j)
        for k in range(1, 60):
            self.assertNotEqual((ar.jdn2cn_day_tiangan(j + k), ar.jdn2cn_day_dizhi(j + k)), pair, k)
        self.assertEqual((ar.jdn2cn_day_tiangan(j + 60), ar.jdn2cn_day_dizhi(j + 60)), pair)


class EnumFlavorTest(unittest.TestCase):
    def test_labels(self):
        self.assertEqual(Tiangan.甲.label, "甲陽木")
        self.assertEqual(Tiangan.癸.label, "癸陰水")
        self.assertEqual(Tiangan.丙.label, "丙陽火")
        self.assertEqual(Dizhi.子.label, "子鼠")
        self.assertEqual(Dizhi.亥.label, "亥豬")
        self.assertEqual(Dizhi.辰.zodiac, "龍")

    def test_yinyang_wuxing_on_both(self):
        self.assertEqual(Dizhi.子.wuxing, "水")
        self.assertEqual(Dizhi.寅.wuxing, "木")
        self.assertEqual(Dizhi.辰.wuxing, "土")
        self.assertEqual(Dizhi.午.wuxing, "火")
        self.assertEqual(Dizhi.申.wuxing, "金")
        self.assertEqual(Dizhi.子.yinyang, "陽")
        self.assertEqual(Dizhi.丑.yinyang, "陰")
        self.assertEqual(Tiangan.庚.wuxing, "金")
        self.assertEqual(Tiangan.己.yinyang, "陰")

    def test_weekday(self):
        self.assertEqual(int(ar.jdn2weekday(2_451_545)), 6)  # 2000-01-01 was a Saturday
        self.assertEqual(ar.jdn2weekday(2_440_588), Weekday.THU)  # 1970-01-01

    def test_cn_month_and_day_structure(self):
        from datex import CnDay, CnMonth

        self.assertEqual(len(CnMonth), 24)
        self.assertFalse(CnMonth.八月.leap)
        self.assertTrue(CnMonth.閏八月.leap)
        self.assertEqual(CnMonth.八月.number, 8)
        self.assertEqual(CnMonth.閏八月.number, 8)
        self.assertEqual(CnMonth.正月.number, 1)
        self.assertEqual(CnMonth.閏十二月.number, 12)
        self.assertEqual(len(CnDay), 30)
        self.assertEqual(CnDay.初一.number, 1)
        self.assertEqual(CnDay.廿九.number, 29)
        self.assertEqual(CnDay.三十.number, 30)
        self.assertEqual(str(Zodiac.VIRGO), "Virgo")  # StrEnum: value is the form
        self.assertEqual(str(CnMonth.閏八月), "閏八月")


class SpanEndInvariantTest(unittest.TestCase):
    """The invariant the whole engine leans on: every from_jdn is constant on
    [j, span_end(j)) with span_end(j) > j. (Changing AT span_end is not
    required — leap's span end is the year boundary by design.)"""

    def _check(self, axes, lo, hi):
        for a in axes:
            j = lo
            while j < hi:
                e = a.span_end(j)
                self.assertGreater(e, j, (a, j))
                v = a.from_jdn(j)
                for k in range(j + 1, min(e, hi)):
                    self.assertEqual(a.from_jdn(k), v, (a, k))
                j = e

    def test_modern_window_all_axes(self):
        lo, hi = ar.civil2jdn(2019, 12, 25), ar.civil2jdn(2021, 1, 10)
        self._check(list(Axis), lo, hi)

    def test_far_future_jie_drift_seam(self):
        # from year 9233 節 terms land in the previous civil December; the
        # month pillar's span end must keep progressing across the seam
        lo, hi = ar.civil2jdn(9232, 12, 1), ar.civil2jdn(9233, 2, 1)
        self._check([Axis.cn_month_tiangan, Axis.cn_month_dizhi], lo, hi)


if __name__ == "__main__":
    unittest.main()
