"""Unit tests for the astronomical (lunisolar) layer.

Goldens were generated by tests/golden/gen_chinese.py and cross-checked
against sxtwl at development time; the modern era (1929-2100) matches sxtwl
day-for-day (pre-1929 divergences are the decreed uniform UTC+8 rule versus
historical Beijing local time)."""

import unittest

from datex import Axis, CnDay, CnMonth, Date, Dizhi, Tiangan, Weekday
from datex import arithmetic as ar
from datex import chinese as ch

_REF = 2_451_545  # 2000-01-01 = 己卯年十一月廿五, 丙子月, 戊午日

# Chinese New Year (正月初一) Gregorian dates per lunar year.
_CNY_GOLDENS = {
    1984: (1984, 2, 2), 1985: (1985, 2, 20), 1986: (1986, 2, 9),
    1987: (1987, 1, 29), 1988: (1988, 2, 17), 1989: (1989, 2, 6),
    1990: (1990, 1, 27), 1991: (1991, 2, 15), 1992: (1992, 2, 4),
    1993: (1993, 1, 23), 1994: (1994, 2, 10), 1995: (1995, 1, 31),
    1996: (1996, 2, 19), 1997: (1997, 2, 7), 1998: (1998, 1, 28),
    1999: (1999, 2, 16), 2000: (2000, 2, 5), 2001: (2001, 1, 24),
    2002: (2002, 2, 12), 2003: (2003, 2, 1), 2004: (2004, 1, 22),
    2005: (2005, 2, 9), 2006: (2006, 1, 29), 2007: (2007, 2, 18),
    2008: (2008, 2, 7), 2009: (2009, 1, 26), 2010: (2010, 2, 14),
    2011: (2011, 2, 3), 2012: (2012, 1, 23), 2013: (2013, 2, 10),
    2014: (2014, 1, 31), 2015: (2015, 2, 19), 2016: (2016, 2, 8),
    2017: (2017, 1, 28), 2018: (2018, 2, 16), 2019: (2019, 2, 5),
    2020: (2020, 1, 25), 2021: (2021, 2, 12), 2022: (2022, 2, 1),
    2023: (2023, 1, 22), 2024: (2024, 2, 10), 2025: (2025, 1, 29),
    2026: (2026, 2, 17), 2027: (2027, 2, 6), 2028: (2028, 1, 26),
    2029: (2029, 2, 13), 2030: (2030, 2, 3), 2031: (2031, 1, 23),
    2032: (2032, 2, 11), 2033: (2033, 1, 31), 2034: (2034, 2, 19),
    2035: (2035, 2, 8), 2036: (2036, 1, 28), 2037: (2037, 2, 15),
    2038: (2038, 2, 4), 2039: (2039, 1, 24), 2040: (2040, 2, 12),
    2041: (2041, 2, 1), 2042: (2042, 1, 22), 2043: (2043, 2, 10),
    2044: (2044, 1, 30), 2045: (2045, 2, 17), 2046: (2046, 2, 6),
    2047: (2047, 1, 26), 2048: (2048, 2, 14), 2049: (2049, 2, 2),
    2050: (2050, 1, 23),
}

# The leap (閏) month number of each lunar year, or None.
_LEAP_GOLDENS = {
    1984: 10, 1985: None, 1986: None, 1987: 6, 1988: None, 1989: None,
    1990: 5, 1991: None, 1992: None, 1993: 3, 1994: None, 1995: 8,
    1996: None, 1997: None, 1998: 5, 1999: None, 2000: None, 2001: 4,
    2002: None, 2003: None, 2004: 2, 2005: None, 2006: 7, 2007: None,
    2008: None, 2009: 5, 2010: None, 2011: None, 2012: 4, 2013: None,
    2014: 9, 2015: None, 2016: None, 2017: 6, 2018: None, 2019: None,
    2020: 4, 2021: None, 2022: None, 2023: 2, 2024: None, 2025: 6,
    2026: None, 2027: None, 2028: 5, 2029: None, 2030: None, 2031: 3,
    2032: None, 2033: 11, 2034: None, 2035: None, 2036: 6, 2037: None,
    2038: None, 2039: 5, 2040: None, 2041: None, 2042: 2, 2043: None,
    2044: 7, 2045: None, 2046: None, 2047: 5, 2048: None, 2049: None,
    2050: 3,
}


class CnyTest(unittest.TestCase):
    def test_cny_goldens(self):
        for y, (gy, gm, gd) in _CNY_GOLDENS.items():
            self.assertEqual(ch.cny_day(y), ar.civil2jdn(gy, gm, gd), y)

    def test_leap_month_goldens(self):
        for y, leap in _LEAP_GOLDENS.items():
            months = [m for (m,) in Date(cn_year=y).project((Axis.cn_month,)) if m.leap]
            if leap is None:
                self.assertEqual(months, [], y)
            else:
                self.assertEqual([m.number for m in months], [leap], y)

    def test_2033_leap_eleven(self):
        # the famously hard case under the modern rule
        self.assertTrue(Date(cn_year=2033, cn_month=CnMonth.閏十一月))


class EvalTest(unittest.TestCase):
    def test_reference_day_all_cn_axes(self):
        row = next(iter(Date(jdn=range(_REF, _REF + 1)).project((
            Axis.cn_year, Axis.cn_year_tiangan, Axis.cn_year_dizhi,
            Axis.cn_month, Axis.cn_month_tiangan, Axis.cn_month_dizhi,
            Axis.cn_day, Axis.cn_day_tiangan, Axis.cn_day_dizhi,
        ))))
        self.assertEqual(
            row,
            (1999, Tiangan.己, Dizhi.卯, CnMonth.十一月, Tiangan.丙, Dizhi.子,
             CnDay.廿五, Tiangan.戊, Dizhi.午),
        )

    def test_cny_day_is_first_of_first_month(self):
        j = ch.cny_day(2026)
        self.assertEqual(ch.jdn2cn_month(j), CnMonth.正月)
        self.assertEqual(ch.jdn2cn_day(j), CnDay.初一)
        self.assertEqual(ch.jdn2cn_year(j), 2026)
        self.assertEqual(ch.jdn2cn_year(j - 1), 2025)

    def test_year_pillar_changes_at_cny(self):
        j = ch.cny_day(2000)  # 2000-02-05: 卯 -> 辰 at CNY, not at 立春
        self.assertEqual(ch.jdn2cn_year_dizhi(j - 1), Dizhi.卯)
        self.assertEqual(ch.jdn2cn_year_dizhi(j), Dizhi.辰)

    def test_month_pillar_changes_at_lichun(self):
        # 立春 2000 fell on Feb 4: 丁丑月 -> 戊寅月
        lichun = ch._jie_days(2000)[1]
        self.assertEqual(ar.jdn2civil(lichun), (2000, 2, 4))
        self.assertEqual(ch.jdn2cn_month_dizhi(lichun - 1), Dizhi.丑)
        self.assertEqual(ch.jdn2cn_month_dizhi(lichun), Dizhi.寅)
        self.assertEqual(ch.jdn2cn_month_tiangan(lichun), Tiangan.戊)

    def test_month_eleven_contains_winter_solstice(self):
        for y in (1999, 2026, 2033):
            ws = ch._jdn_of_jde(ch._winter_solstice_jde(y))
            self.assertEqual(ch.jdn2cn_month(ws).number, 11, y)
            self.assertFalse(ch.jdn2cn_month(ws).leap, y)


class ConstraintTest(unittest.TestCase):
    def _days(self, d):
        return sum(len(r) for (r,) in d.project((Axis.jdn,)))

    def test_lunar_year_is_exact_interval(self):
        d = Date(cn_year=1999)
        self.assertEqual(self._days(d), ch.cny_day(2000) - ch.cny_day(1999))
        self.assertIn(_REF, d)
        self.assertNotIn(_REF, Date(cn_year=2000))

    def test_month_lengths(self):
        self.assertEqual(self._days(Date(cn_year=1999, cn_month=CnMonth.八月)), 29)
        for y in (1999, 2020, 2033):
            n = self._days(Date(cn_year=y))
            self.assertIn(n, (353, 354, 355, 383, 384, 385), y)

    def test_string_constraints(self):
        self.assertIn(_REF, Date(cn_month="十一月", cn_day="廿五"))
        self.assertNotIn(_REF, Date(cn_month="閏八月"))

    def test_membership_over_large_finite_windows(self):
        d = Date(cn_day="初一", jdn=range(1, 6_000_000))
        self.assertIn(ch.cny_day(2000), Date(cn_day="初一"))
        self.assertNotIn(ch.cny_day(2000) + 5, d)

    def test_infinite_astro_truthiness_by_drift_recurrence(self):
        self.assertTrue(Date(cn_month=CnMonth.八月))

    def test_certified_incompatibility_is_empty(self):
        # lunisolar 正月 can only touch 節氣 months 丑/寅/卯
        self.assertFalse(Date(cn_month="正月", cn_month_dizhi=Dizhi.酉))
        self.assertTrue(Date(cn_month="正月", cn_month_dizhi=Dizhi.寅))

    def test_joint_projection(self):
        pairs = list(Date(cn_year=2020).project((Axis.cn_month, Axis.cn_month_dizhi)))
        # 13 lunisolar months in leap 2020, each spanning exactly two 節氣 branches
        self.assertEqual(len(pairs), 26)
        for m, dz in pairs:
            self.assertIsInstance(m, CnMonth)
            self.assertIsInstance(dz, Dizhi)

    def test_compat_table_is_sound_locally(self):
        # every observed (lunisolar month, 節氣-branch) pair must be allowed
        from datex.core import _compatible

        for j in range(ch.cny_day(2018), ch.cny_day(2028)):
            self.assertTrue(_compatible(ch.jdn2cn_month(j), ch.jdn2cn_month_dizhi(j)), j)


class AstroAlgebraTest(unittest.TestCase):
    def test_union_with_astro_works(self):
        d = Date(cn_year=1999) & (Date(cn_month="八月") | Date(cn_month="九月"))
        n = sum(len(r) for (r,) in d.project((Axis.jdn,)))
        self.assertEqual(n, 29 + 30)

    def test_astro_set_laws(self):
        a, b = Date(cn_month="八月"), Date(cn_month=["八月", "九月"])
        self.assertFalse(a ^ a)
        self.assertLess(a, b)
        self.assertEqual(a | Date(cn_month="九月"), b)
        self.assertFalse(a <= Date(weekday=Weekday.MON))  # decree decides

    def test_difference_with_astro_works(self):
        a = Date(cn_year=1999)
        b = Date(cn_month="八月")
        left = sum(len(r) for (r,) in (a - b).project((Axis.jdn,)))
        both = sum(len(r) for (r,) in (a & b).project((Axis.jdn,)))
        whole = sum(len(r) for (r,) in a.project((Axis.jdn,)))
        self.assertEqual(left, whole - both)


if __name__ == "__main__":
    unittest.main()
